#fontforge ../../scripts/fontconvert experiment-latin-0.sfd --remove-overlap --unlink-reference --otf
#fontforge ../../scripts/fontconvert experiment-latin-1.sfd --remove-overlap --unlink-reference --otf
fontforge ../../scripts/fontconvert experiment-sinhala-0.sfd --remove-overlap --unlink-reference --otf
#fontforge ../../scripts/fontconvert experiment-sinhala-1.sfd --remove-overlap --unlink-reference --otf
fontforge ../../scripts/fontconvert experiment-sinhala-cursive-0.sfd --remove-overlap --unlink-reference --otf
fontforge ../../scripts/fontconvert experiment-sinhala-cursive-1.sfd --remove-overlap --unlink-reference --otf
#fontforge ../../scripts/fontconvert experiment-sinhala-italic-0.sfd --remove-overlap --unlink-reference --otf
#fontforge ../../scripts/fontconvert experiment-tamil-0.sfd --remove-overlap --unlink-reference --otf
#fontforge ../../scripts/fontconvert experiment-tamil-italic-0.sfd --remove-overlap --unlink-reference --otf
#fontforge ../../scripts/fontconvert experiment-thaana-0.sfd --remove-overlap --unlink-reference --otf
#fontforge ../../scripts/fontconvert experiment-thaana-1.sfd --remove-overlap --unlink-reference --otf
